services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - ../:/workspace
    command: sleep infinity

  # Populate a volume simply to be used in the guide. Eventually, this won't be needed
  # once the volume mounting mutation works correctly.
  db-volume-setup:
    image: alpine
    command: cp /sample-data/test.db /data
    volumes:
      - sqlite-data:/data
      - ../chatbot/sample-data:/sample-data

volumes:
  sqlite-data:
    name: sqlite-data